services:
  redis:
    image: redis
    ports:
      - '6379:6379'
  web:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis