services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  flask:
      build: .
      container_name: flask
      ports:
        - "8080:8080"
      volumes:
        - .:/app
      depends_on:
        - redis


